### ISSUE TITLE
代码使用

### ISSUE THREAD

**Issue by JMbaozi** [PrimerLi/red_chamber_dream_network#1]
你好，我最近正在写一遍关于《红楼梦》社交网络的文章，可以使用你的Parser.scala代码么？

**Comment by PrimerLi** [comment]
可以，欢迎使用

**Comment by JMbaozi** [comment]
作者，我又回来了，我没有接触过scala，你可否讲解一下这个程序是如何计算出每条边的权重weight？谢谢你。

**Comment by PrimerLi** [comment]
我用的是计算每一段中人物出场的次数，然后将所有的段落加起来。
举例说明
《红楼梦》的两段原文：

李纨道：“就是这样好．但序齿我大，你们都要依我的主意，管情说了大家合意．我们七个人起社，我和二姑娘四姑娘都不会作诗，须得让出我们三个人去．我们三个各分一件事。”探春笑道：“已有了号，还只管这样称呼，不如不有了．以后错了，也要立个罚约才好。”李纨道：“立定了社，再定罚约．我那里地方大，竟在我那里作社．我虽不能作诗，这些诗人竟不厌俗客，我作个东道主人，我自然也清雅起来了．若是要推我作社长，我一个社长自然不够，必要再请两位副社长，就请菱洲藕榭二位学究来，一位出题限韵，一位誊录监场．亦不可拘定了我们三个人不作，若遇见容易些的题目韵脚，我们也随便作一首．你们四个却是要限定的．若如此便起，若不依我，我也不敢附骥了。”迎春惜春本性懒于诗词，又有薛林在前，听了这话便深合己意，二人皆说：“极是"．探春等也知此意，见他二人悦服，也不好强，只得依了．因笑道：“这话也罢了，只是自想好笑，好好的我起了个主意，反叫你们三个来管起我来了。”宝玉道：“既这样，咱们就往稻香村去。”李纨道：“都是你忙，今日不过商议了，等我再请。”宝钗道：“也要议定几日一会才好．"探春道：“若只管会的多，又没趣了．一月之中，只可两三次才好。”宝钗点头道：“一月只要两次就够了。”拟定日期，风雨无阻．除这两日外，倘
有高兴的，他情愿加一社的，或情愿到他那里去，或附就了来，亦可使得，岂不活泼有趣。”众人都道：“这个主意更好。”


探春道：“只是原系我起的意，我须得先作个东道主人，方不负我这兴。”李纨道：“既这样说，明日你就先开一社如何？"探春道：“明日不如今日，此刻就很好．你就出题，菱洲限韵，藕榭监场。”迎春道：“依我说，也不必随一人出题限韵，竟是拈阄公道。”李纨道：“方才我来时，看见他们抬进两盆白海棠来，倒是好花．你们何不就咏起他来？"迎春道：“都还未赏，先倒作诗。”宝钗道：“不过是白海棠，又何必定要见了才作．古人的诗赋，也不过都是寄兴写情耳．若都是等见了作，如今也没这些诗了。”迎春道：“既如此，待我限韵。”说着，走到书架前抽出一本诗来，随手一揭，这首竟是一首七言律，递与众人看了，都该作七言律．迎春掩了诗，又向一个小丫头道：“你随口说一个字来。”那丫头正倚门立着，便说了个"门"字．迎春笑道：“就是门字韵，`十三元-了．头一个韵定要这`门-字
。”说着，又要了韵牌匣子过来，抽出"十三元"一屉，又命那小丫头随手拿四块．那丫头便拿了"盆”“魂”“痕”“昏"四块来．宝玉道：“这`盆-`门-两个字不大好作呢！”

我通过识别人名来分析每个人物的出场次数。第一段里面，"李纨"出现了三次，"探春"出现了三次，"宝玉"出现了一次，"迎春"出现了一次，“惜春”出现了一次，“宝钗”出现了两次，两个人共同出现在一个场景中，他们之间就连一条边，边的权重为他们共同出现的次数。于是我们就有下面的边信息：
李纨 -- 探春， weight = 3
李纨 -- 宝玉，weight = 1
李纨 -- 迎春，weight = 1
李纨 -- 惜春，weight = 1
李纨 -- 宝钗，weight = 2
探春 -- 宝玉，weight = 1
探春 -- 迎春，weight = 1
探春 -- 惜春，weight = 1
探春 -- 宝钗，weight = 2
宝玉 -- 迎春，weight = 1
宝玉 -- 惜春，weight = 1
宝玉 -- 宝钗，weight = 1
宝钗 -- 迎春，weight = 1
宝钗 -- 惜春，weight = 1
迎春 -- 惜春，weight = 1

第二段里面，“宝玉”出现一次，“探春”出现两次，“李纨”出现两次，"迎春"出现了五次，"宝钗"出现了一次，可以得到如下的边：
宝玉 -- 探春，weight = 1
宝玉 -- 李纨，weight = 1
宝玉 -- 迎春， weight = 1
宝玉 -- 宝钗，weight = 1
探春 -- 李纨，weight = 2
探春 -- 迎春，weight = 2
探春 -- 宝钗，weight = 1
李纨 -- 迎春，weight = 2
李纨 -- 宝钗，weight = 1
迎春 -- 宝钗，weight = 1

每条边都是无向的。
将上面两段的边合并，就得到这两段的总的边信息。
如何合并两条边?
举例
第一段里面有这样的一条边：“李纨 -- 探春，weight = 3”， 第二段里面又有这样的一条边：“探春 -- 李纨，weight =
2"，两条边合并，注意边是无向的，所以可以得到一条新的边，为 "李纨 -- 探春，weight = 5".


使用上面的算法分析《红楼梦》中所有的段落，对每一段都可以得到一个边的集合，最终将所有的边合并，就得到最后的结果。

希望对你有用.

**Comment by JMbaozi** [comment]
顿时开朗，谢谢你！
